public class PromptGenerator
{
    private readonly List<string> _prompts =
   [
       "Who was the most interesting person I interacted with today?",
       "What was the best part of my day?",
       "How did I see the hand of the Lord in my life today?",
       "What was the strongest emotion I felt today?",
       "If I had one thing I could do over today, what would it be?",
       "What am I grateful for today?",
       "What challenges did I face today and how did I overcome them?",
       "Who made me smile today and why?",
       "What is one thing I learned today?",
       "What did I do today that I am proud of?",
       "How did I show kindness to someone today?",
       "What is a goal I accomplished today?",
       "What is something that inspired me today?",
       "What is one thing I want to improve about myself?",
       "What did I do to take care of myself today?",
       "What new experience did I have today?",
       "How did I connect with nature today?",
       "What is something I want to achieve tomorrow?",
       "What was a memorable moment from today?",
       "How did I feel when I woke up this morning?",
       "What is something I did today to help someone else?",
       "What book, movie, or show had an impact on me today?",
       "What was a challenge I faced today?",
       "How did I overcome a fear today?",
       "What made me feel happy today?",
       "What are my dreams and aspirations?",
       "What is something creative I did today?",
       "How did I practice patience today?",
       "What is a decision I made today and what led me to make it?",
       "What did I learn from a mistake I made today?",
       "Who did I share a meaningful conversation with today?",
       "What is a highlight from my day?",
       "How did I practice gratitude today?",
       "What new thing did I try today?",
       "What is something I am looking forward to?",
       "What was a moment of peace I experienced today?",
       "How did I practice self-love today?",
       "What is something that challenged my thinking today?",
       "What did I do today that I will remember for a long time?",
       "How did I handle stress today?",
       "What did I do to make myself happy today?",
       "What is something I found beauty in today?",
       "What did I appreciate about myself today?",
       "What was a surprising moment from today?",
       "How did I show love to someone today?",
       "What is a question I pondered today?",
       "What was a small victory I had today?",
       "What did I let go of today?",
       "How did I practice mindfulness today?",
       "What is something I am grateful for about my body?",
       "What did I learn about myself today?",
       "What is a memory from today that I want to keep?",
       "What was a moment of laughter I had today?",
       "How did I make today special?",
       "What is something I accomplished today?",
       "What did I do to feel connected to others today?",
       "What is a risk I took today?",
       "How did I show courage today?",
       "What is something I am proud of today?",
       "What did I do to relax today?",
       "What did I appreciate about nature today?",
       "What is something I did today that was out of my comfort zone?",
       "How did I challenge myself today?",
       "What did I do today that I enjoyed?",
       "What did I do to make someone's day better?",
       "What is a lesson I learned today?",
       "What did I do to make myself feel good today?",
       "How did I show compassion today?",
       "What is something I want to remember from today?",
       "How did I practice forgiveness today?",
       "What did I do to take care of my mental health today?",
       "What did I do to take care of my physical health today?",
       "What is a goal I set for myself today?",
       "What did I do to feel productive today?",
       "What did I do to feel relaxed today?",
       "What did I appreciate about my surroundings today?",
       "What is something I am excited about?",
       "How did I feel at the end of the day?",
       "What did I do to challenge my mind today?",
       "What is something I want to do tomorrow?",
       "What was a moment of joy I experienced today?",
       "What did I do to nurture my relationships today?",
       "What is something I did today that I am grateful for?",
       "What was a moment of clarity I had today?",
       "What did I do to make myself feel accomplished today?",
       "How did I show self-discipline today?",
       "What is something I appreciated about today?",
       "What did I do to be kind to myself today?",
       "How did I make progress towards my goals today?",
       "What is something I found peace in today?",
       "What did I do to be present in the moment today?",
       "What is something I did today that I want to continue doing?",
       "How did I show resilience today?",
       "What did I do to embrace change today?",
       "What is something I am thankful for today?",
       "How did I find balance in my life today?",
       "What did I do to feel fulfilled today?",
       "What is something I did today that I want to build on?",
       "How did I express my creativity today?"
   ];


    public string GetRandomPrompt()
    {
        Random random = new();
        int index = random.Next(_prompts.Count);
        return _prompts[index];
    }
}